# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      go-production:
        dependency-type: "production"
      go-development:
        dependency-type: "development"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"

  # npm (dashboards)
  - package-ecosystem: "npm"
    directory: "/dashboards/admin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/dashboards/user"
    schedule:
      interval: "weekly"
