global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'qstack'
    static_configs:
      - targets:
          - 'qstack-api:8080'
          - 'qstack-storage:8081'
          - 'qstack-network:8082'
          - 'qstack-image:8083'
          - 'qstack-billing:8084'
          - 'qstack-backup:8085'
          - 'qstack-ai:8086'
